### ISSUE TITLE
Can't get ameba to compile on macOS 12.6

### ISSUE THREAD

**Issue by tjbarber** [crystal-ameba/ameba#285]
Hey y'all, I'm struggling to get ameba to compile on an M1 Mac. I've installed `crystal` through `brew`. This is my output when I run `make`.

```
➜  ameba git:(master) make
shards build -Dpreview_mt
Dependencies are satisfied
Building: ameba
Error target ameba failed to compile:
Undefined symbols for architecture arm64:
  "_EVP_MD_size", referenced from:
      _*Digest::SHA1@OpenSSL::Digest#digest_size:Int32 in D-igest5858S-H-A-1.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Error: execution of command failed with code: 1: `cc "${@}" -o /Users/tjbarber/Projects/ameba/bin/ameba  -rdynamic -L/opt/homebrew/lib -L/usr/lib `command -v pkg-config > /dev/null && pkg-config --libs --silence-errors libssl || printf %s '-lssl -lcrypto'` `command -v pkg-config > /dev/null && pkg-config --libs --silence-errors libcrypto || printf %s '-lcrypto'` -L/opt/homebrew/Cellar/libyaml/0.2.5/lib -lyaml -lpcre -lgc -L/opt/homebrew/Cellar/libevent/2.1.12/lib -levent_pthreads -levent -L/opt/homebrew/Cellar/libevent/2.1.12/lib -levent -liconv`

make: *** [bin/ameba] Error 1
```

This is my `crystal env`:

```
CRYSTAL_CACHE_DIR=/Users/tjbarber/.cache/crystal
CRYSTAL_PATH=lib:/opt/homebrew/Cellar/crystal/1.6.1/libexec/../share/crystal/src
CRYSTAL_VERSION=1.6.1
CRYSTAL_LIBRARY_PATH=/opt/homebrew/lib:/usr/lib
CRYSTAL_OPTS=''
```

Here is my `brew list`, just in case I'm missing a dependency (I don't think I am, this seems like a linking issue with openssl?):

```
➜  ameba git:(master) brew list
==> Formulae
apr			ctags			gradle@6		libpthread-stubs	libyaml			openjdk			readline		xorgproto
apr-util		elasticsearch-full	graphite2		libtiff			little-cms2		openjdk@11		redis			xz
autoconf		fontconfig		harfbuzz		libtool			llvm@11			openssl@1.1		ruby-build		z3
automake		freetype		heroku			libx11			llvm@14			openssl@3		screenresolution	zstd
bat			fzf			heroku-node		libxau			lolcat			pcre			six
bdw-gc			gdbm			icu4c			libxcb			lz4			pcre2			sqlite
ca-certificates		gettext			jpeg-turbo		libxdmcp		lzo			pixman			subversion
cairo			giflib			libevent		libxext			m4			pkg-config		the_silver_searcher
coreutils		glib			libiconv		libxml2			mpdecimal		python@3.10		unixodbc
crystal			gmp			libpng			libxrender		neofetch		rbenv			utf8proc

==> Casks
brave-browser	discord		firefox		iterm2		macvim		ngrok		postico		vlc		vscodium
```

**Comment by Sija** [comment]
That's a problem with your crystal installation, there's nothing to do here from the ameba's side.

**Comment by veelenga** [comment]
@tjbarber i don't think it is related to M1 / macOS 12.6. I have the same setup and it compiles successfully on my end.

**Comment by straight-shoota** [comment]
@tjbarber It looks like you're either missing libcrypto or the version you have installed is incompatible. You can get assistance for this problem at https://forum.crystal-lang.org/ or in one of the community chats (https://crystal-lang.org/community/#chat).

**Comment by straight-shoota** [comment]
@veelenga @Sija The problem is likely caused by a missing lib dependency.
But there's actually no mention in the [installation instructions](https://github.com/crystal-ameba/ameba#installation) that ameba requires libcrypto. It does so by using `Digest::SHA1` which is based on OpenSSL. So it's not a direct dependency, but through stdlib. Still, libcrypto is an optional dependency for stdlib and applications that use it should better mention that for complete installation instructions.

**Comment by straight-shoota** [comment]
Ideally, ameba shouldn't depend on libcrypto. A native Crystal implementation would be much easier and avoid an unnecessary dependency. Stdlib currently has no crypographic hash algorithm implemented in native Crystal, though. 

But the only use of `Digest` in ameba is this:
https://github.com/crystal-ameba/ameba/blob/f288cc3c4f060630748832778fb2d73f340c8fb1/src/ameba/runner.cr#L210
I'm pretty sure a checksum for recognizing duplicates does not need a cryptographic hash. `String#hash` should suffice for that.

**Comment by Sija** [comment]
@straight-shoota Good catch, thanks! We definitely shouldn't depend on _libcrypto_, I can prepare a PR fixing that.

ftr, this dependency was silently introduced in #248.
