### ISSUE TITLE
undefined constant Crystal::ThreadLocalValue on Windows

### ISSUE THREAD

**Issue by jwoertink** [crystal-ameba/ameba#359]
Not sure if this is a Crystal specific issue, but I'll start here...

Ameba 1.0.0 actually works well on Windows https://github.com/luckyframework/lucky_env/actions/runs/4025239619/jobs/6918285632 but when trying 1.4.0, I get some compilation errors https://github.com/luckyframework/lucky_router/actions/runs/4217723196/jobs/7321714423

```
Failed postinstall of ameba on make bin && make run_file:
shards build -Dpreview_mt

Dependencies are satisfied

Building: ameba

Error target ameba failed to compile:

Showing last frame. Use --error-trace for full trace.


There was a problem expanding macro 'macro_2497926223616'


Code in D:\a\_temp\crystal-latest-true-undefined\src\reference.cr:140:5


 140 | {% if flag?(:preview_mt) %}

       ^

Called macro defined in D:\a\_temp\crystal-latest-true-undefined\src\reference.cr:140:5


 140 | {% if flag?(:preview_mt) %}


Which expanded to:


 > 1 | 

 > 2 |       @@exec_recursive = Crystal::ThreadLocalValue(Registry).new

                                ^------------------------

Error: undefined constant Crystal::ThreadLocalValue

mingw32-make: *** [makefile:9: build] Error 1
Error: Process completed with exit code 1.
```

**Comment by Sija** [comment]
Which version of Crystal you're running it with?

**Comment by Sija** [comment]
Most likely it's caused by https://github.com/crystal-ameba/ameba/pull/269 - triggering https://github.com/crystal-lang/crystal/blob/ec257b0b67732d1e8f1a71e42fece2df2394ce60/src/reference.cr#L141.

It doesn't seem to be specifically ameba-related. I'd open an issue on the Crystal bug tracker instead.

**Comment by jwoertink** [comment]
Ah nice catch! Yeah, I'm running Crystal 1.7.2. Thanks for the quick fix!

**Comment by Sija** [comment]
Fix will be shipped as a part of Crystal 1.8.0 release, closing.
