### PR TITLE
fix restriction issue

### PR DESCRIPTION
**Pull request by mamantoha**
caused by https://github.com/crystal-lang/crystal/pull/12335

Ameba fails on Crystal Nightly. For example https://github.com/mamantoha/crest/runs/7602787403?check_suite_focus=true

```
In src/ameba/inline_comments.cr:41:56

 41 | return false unless line_number = location.try &.line_number.try &.- 1
                                                       ^----------
Error: Error: undefined method 'line_number' for Tuple(Int32, Int32)

make: *** [Makefile:8: bin/ameba] Error 1
```

### CODE REVIEW

File: src/ameba/reportable.cr [hunk 1]
```diff
@@ -5,7 +5,12 @@ module Ameba
     getter issues = [] of Issue
 
     # Adds a new issue to the list of issues.
-    def add_issue(rule, location, end_location, message, status : Issue::Status? = nil, block : (Source::Corrector ->)? = nil) : Issue
+    def add_issue(rule,
+                  location : Crystal::Location?,
+                  end_location,
+                  message,
```
Comment (Sija) [inline src/ameba/reportable.cr:11]:
```suggestion
                  end_location : Crystal::Location?,
                  message : String,
```

File: src/ameba/reportable.cr [hunk 2]
```diff
@@ -15,7 +20,12 @@ module Ameba
     end
 
     # :ditto:
-    def add_issue(rule, location, end_location, message, status : Issue::Status? = nil, &block : Source::Corrector ->) : Issue
+    def add_issue(rule,
+                  location : Crystal::Location,
+                  end_location,
+                  message,
```
Comment (Sija) [inline src/ameba/reportable.cr:26]:
```suggestion
                  end_location : Crystal::Location?,
                  message : String,
```

**Review by Sija — COMMENTED** [review]
While we're at it, let's add type restrictions to the remaining arguments.

**Review by Sija — APPROVED** [review]

File: src/ameba/reportable.cr [hunk 3]
```diff
@@ -15,7 +20,12 @@ module Ameba
     end
 
     # :ditto:
-    def add_issue(rule, location, end_location, message, status : Issue::Status? = nil, &block : Source::Corrector ->) : Issue
+    def add_issue(rule,
+                  location : Crystal::Location,
+                  end_location : Crystal::Location?,
```
[the remark this answers is not in the document]
Comment (mamantoha) [reply src/ameba/reportable.cr]: changed

**Comment by Sija** [comment]
@veelenga Looks like a good time for a `1.0.1` release :)
